import { jsPDF } from "jspdf";
import autoTable from "jspdf-autotable";
import { supabase } from "@/integrations/supabase/client";

interface InvoiceData {
  invoice_number: string;
  created_at: string;
  kind?: "proforma" | "final";
  supplier: { name: string; phone: string; shop_name?: string | null };
  retailer: { name: string; phone: string; shop_name?: string | null };
  items: { name: string; qty: number; unit: string; price: number; total: number }[];
  total: number;
}

export function publicInvoiceUrl(code: string): string {
  return `${window.location.origin}/i/${encodeURIComponent(code)}`;
}

export function generateInvoicePdf(data: InvoiceData): Blob {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  const isProforma = data.kind === "proforma";

  // Header
  doc.setFillColor(15, 15, 18);
  doc.rect(0, 0, w, 32, "F");
  doc.setTextColor(255, 153, 51);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("STOCKFLOW", 14, 14);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(isProforma ? "PROFORMA" : "INVOICE", 14, 22);
  doc.setFontSize(10);
  doc.text(data.invoice_number, w - 14, 14, { align: "right" });
  doc.setFontSize(8);
  doc.text(new Date(data.created_at).toLocaleString(), w - 14, 22, { align: "right" });

  let partiesY = 44;
  if (isProforma) {
    doc.setFillColor(255, 240, 200);
    doc.rect(0, 32, w, 8, "F");
    doc.setTextColor(120, 80, 0);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.text("PROFORMA — NOT A TAX INVOICE", w / 2, 38, { align: "center" });
    partiesY = 50;
  }

  // Parties
  doc.setTextColor(20, 20, 20);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text("FROM", 14, partiesY);
  doc.text("TO", w / 2 + 4, partiesY);
  doc.setFont("helvetica", "normal");
  doc.text(data.supplier.shop_name || data.supplier.name, 14, partiesY + 6);
  doc.text(`Ph: ${data.supplier.phone}`, 14, partiesY + 12);
  doc.text(data.retailer.shop_name || data.retailer.name, w / 2 + 4, partiesY + 6);
  doc.text(`Ph: ${data.retailer.phone}`, w / 2 + 4, partiesY + 12);

  autoTable(doc, {
    startY: partiesY + 22,
    head: [["#", "Item", "Qty", "Unit", "Price", "Total"]],
    body: data.items.map((it, i) => [
      String(i + 1), it.name, String(it.qty), it.unit, `INR ${it.price.toFixed(2)}`, `INR ${it.total.toFixed(2)}`,
    ]),
    headStyles: { fillColor: [255, 153, 51], textColor: 20 },
    styles: { fontSize: 9 },
  });

  const finalY = (doc as any).lastAutoTable.finalY + 10;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text(`Total: INR ${data.total.toFixed(2)}`, w - 14, finalY, { align: "right" });

  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(100);
  doc.text(
    isProforma
      ? "Generated by StockFlow · Estimate only — final invoice will follow after supplier confirms."
      : "Generated by StockFlow · Final invoice — quantities and prices set by supplier.",
    14, doc.internal.pageSize.getHeight() - 10,
  );

  return doc.output("blob");
}

export async function uploadInvoicePdf(invoiceId: string, blob: Blob): Promise<string> {
  const path = `${invoiceId}/invoice.pdf`;
  const { error } = await supabase.storage.from("invoices").upload(path, blob, { upsert: true, contentType: "application/pdf" });
  if (error) throw error;
  // Signed URL valid 7 days (kept for backwards compat / direct downloads)
  const { data, error: urlErr } = await supabase.storage.from("invoices").createSignedUrl(path, 60 * 60 * 24 * 7);
  if (urlErr) throw urlErr;
  return data.signedUrl;
}
